-- -- Create testimonials table for customer reviews
-- CREATE TABLE IF NOT EXISTS testimonials (
--     id SERIAL PRIMARY KEY,
--     customer_name VARCHAR(200) NOT NULL,
--     customer_role VARCHAR(200),
--     customer_avatar TEXT,
--     review_text TEXT NOT NULL,
--     rating INTEGER DEFAULT 5 CHECK (rating >= 1 AND rating <= 5),
--     is_featured BOOLEAN DEFAULT false,
--     is_active BOOLEAN DEFAULT true,
--     sort_order INTEGER DEFAULT 0,
--     created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
--     updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
-- );

-- -- Insert default testimonials
-- INSERT INTO testimonials (customer_name, customer_role, customer_avatar, review_text, rating, is_featured, is_active, sort_order) VALUES
-- ('Isabella Rodriguez', 'Food Critic', '/placeholder.svg?height=80&width=80', 'Every bite at Lumière is a revelation. The flavors, presentation, and service are simply world-class. This restaurant has redefined my understanding of fine dining.', 5, true, true, 1),
-- ('Daniel Kim', 'Sommelier', '/placeholder.svg?height=80&width=80', 'An exceptional wine list paired with dishes that elevate every sip—truly unparalleled. The attention to detail in both food and wine pairings is extraordinary.', 5, true, true, 2),
-- ('Sophia Martinez', 'Travel Blogger', '/placeholder.svg?height=80&width=80', 'The ambiance alone is worth the visit, but the cuisine makes it an experience I''ll never forget. Every element comes together to create pure magic.', 5, true, true, 3),
-- ('James Thompson', 'Chef', '/placeholder.svg?height=80&width=80', 'As a fellow chef, I can appreciate the incredible technique and creativity on display here. This is culinary artistry at its finest.', 5, false, true, 4),
-- ('Maria Santos', 'Food Enthusiast', '/placeholder.svg?height=80&width=80', 'From the moment we walked in, we knew we were in for something special. The service was impeccable and every dish was a masterpiece.', 5, false, true, 5)
-- ON CONFLICT DO NOTHING;
